stages:
  - deploy

deploy_to_server:
  stage: deploy

  tags:
    - shell

  rules:
    - if: $CI_COMMIT_BRANCH == "main"

  script:
    - echo "Nieuwe code is gedetecteerd en gedownload op de server."

    - echo "SMARTSCHOOL_CLIENT_ID=$SMARTSCHOOL_CLIENT_ID" > .env
    - echo "SMARTSCHOOL_CLIENT_SECRET=$SMARTSCHOOL_CLIENT_SECRET" >> .env
    
    - echo "APIKEY" >> .env

    - docker compose up -d --build --remove-orphans

  environment:
    name: production
