import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
      <img src="https://helpdesk.go-antwerpen.be/logo.php" className="goLogo" />
    </header>
    <nav>
      <button>Startpagina</button>
      <button>Catalogus</button>
      <button>Mijn uitleningen</button>
      <button>Mijn leeslijst & favorieten</button>
      </nav>
      <div id="backgroundImage"></div>
        {children}
      <footer>
        <div id="socialMediaBlock">
          <h4>Sociale media</h4>
          <a href="https://www.instagram.com/go_scholengroep_antwerpen/" id="instagram" className="socialMediaLogo"></a>
          <a href="https://www.facebook.com/GOAntwerpen/" id="facebook" className="socialMediaLogo"></a>
          <a href="https://x.com/GOinAntwerpen" id="twitter" className="socialMediaLogo"></a>
          <a href="https://www.linkedin.com/company/go-scholengroep-antwerpen/" id="linkedIn" className="socialMediaLogo"></a>
          <a href="https://www.youtube.com/channel/UCDdFd-gH1DbonyHgBqyBUWQ" id="youtube" className="socialMediaLogo"></a>
        </div>
        <img src="https://helpdesk.go-antwerpen.be/logo.php" className="goLogoFooter" />
        <div id="contactBlock">
          <h4>Contact</h4>
          <p>GO! Scholengroep Antwerpen</p>
          <p>Thonetlaan 106A</p>
          <p>2050 Antwerpen</p>
          <p>secretariaat@go-antwerpen.be</p>
          <p>03 360 82 90</p>
        </div>
        <div id="linksBlock">
          <h4>Nuttige links</h4>
          <ul>
            <li><a href="https://g-o.be/">GO! onderwijs</a></li>
            <li><a href="https://meldjeaan.antwerpen.be/">Meld je aan Antwerpen</a></li>
            <li><a href="https://go-antwerpen.smartschool.be/login">Smartschool</a></li>
            <li><a href="https://onderwijs.vlaanderen.be/">Onderwijs Vlaanderen</a></li>
            <li><a href="https://www.onderwijskiezer.be/v2/index.php">Onderwijskiezer</a></li>
            <li><a href="https://www.taalkrachtgoantwerpen.be/">Taalkracht GO! Antwerpen</a></li>
          </ul>
        </div>
      </footer>
      </body>
    </html>
  );
}
