import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <img
            src="https://helpdesk.go-antwerpen.be/logo.php"
            className="goLogo"
          />
        </header>
        <nav>
          <button>Startpagina</button>
          <Link href="/catalog">
            <button>Catalogus</button>
          </Link>
          <button>Mijn uitleningen</button>
          <button>Mijn leeslijst & favorieten</button>
        </nav>
        <div id="backgroundImage"></div>
        {children}
      </body>
    </html>
  );
}
