app.frontend.base-url=https://gosmartbib.tech
spring.security.oauth2.client.registration.smartschool.redirect-uri=https://gosmartbib.tech/api/login/oauth2/code/smartschool
app.mock-role.enabled=false
admin.seed.username=${ADMIN_USERNAME}
admin.seed.password-hash=${ADMIN_PASSWORD_HASH}
