package edu.ap.gosmartlib.util;

import edu.ap.gosmartlib.entities.bookEntities.BookCopyEntity;
import edu.ap.gosmartlib.entities.bookEntities.BookEntity;
import edu.ap.gosmartlib.entities.bookEntities.BookInventoryEntity;
import edu.ap.gosmartlib.repositories.bookRepositories.BookCopyRepository;
import edu.ap.gosmartlib.repositories.bookRepositories.BookInventoryRepository;
import edu.ap.gosmartlib.repositories.bookRepositories.BookRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import edu.ap.gosmartlib.entities.bookEntities.BookInventoryEntity;
import edu.ap.gosmartlib.entities.schoolEntities.SchoolEntity;
import edu.ap.gosmartlib.repositories.schoolRepositories.SchoolRepository;

import java.util.ArrayList;
import java.util.List;

@Component
public class DataSeeding implements CommandLineRunner {
        private final BookRepository bookRepository;
        private final BookInventoryRepository bookInventoryRepository;
        private final BookCopyRepository bookCopyRepository;
        private final SchoolRepository schoolRepository;
        private final edu.ap.gosmartlib.services.BookService bookService;
        private static final Logger logger = LoggerFactory.getLogger(DataSeeding.class);

        private SchoolEntity seedSchoolPrimary;
        private SchoolEntity seedSchoolSecondary;

        public DataSeeding(BookRepository bookRepository, BookInventoryRepository bookInventoryRepository,
                        BookCopyRepository bookCopyRepository, SchoolRepository schoolRepository,
                        edu.ap.gosmartlib.services.BookService bookService) {
                this.bookRepository = bookRepository;
                this.bookInventoryRepository = bookInventoryRepository;
                this.bookCopyRepository = bookCopyRepository;
                this.schoolRepository = schoolRepository;
                this.bookService = bookService;
        }

        private String mapAgeRange(String readingLevel) {
                return switch (readingLevel) {
                        case "A", "B" -> "Eerste graad";
                        case "C" -> "Tweede graad";
                        case "D" -> "Derde graad";
                        default -> "Tweede graad";
                };
        }

        private String normalizeLanguage(String language) {
                if (language == null || language.isBlank()) {
                        return "nl";
                }

                return switch (language.trim().toLowerCase()) {
                        case "ne", "nl", "nederlands", "dutch" -> "nl";
                        case "en", "engels", "english" -> "en";
                        case "fr", "frans", "french" -> "fr";
                        default -> "nl";
                };
        }

        private BookEntity book(
                        String title,
                        List<String> authors,
                        String publisher,
                        String description,
                        int pageCount,
                        List<String> categories,
                        String thumbnail,
                        String language,
                        double rating,
                        String isbn,
                        Integer publishedYear,
                        boolean spotlight,
                        boolean didacticTag,
                        List<String> labels,
                        String readingLevel,
                        Integer totalCopies,
                        Integer availableCopies) {
                String ageRange = mapAgeRange(readingLevel);
                BookEntity b = new BookEntity(
                                title,
                                authors,
                                publisher,
                                description,
                                pageCount,
                                categories,
                                thumbnail,
                                normalizeLanguage(language),
                                rating,
                                isbn,
                                publishedYear,
                                didacticTag,
                                labels,
                                readingLevel,
                                totalCopies,
                                availableCopies,
                                ageRange);
                b.setSpotlight(spotlight);

                // AANGEPAST: Geef de previewLink in deze mock data standaard null
                // Als gebruikers via de app op ISBN boeken toevoegen, wordt dit veld door
                // BookService ingevuld via de Google API
                b.setPreviewLink(null);

                List<BookInventoryEntity> inventories = createSeedInventories(b, totalCopies, availableCopies);
                b.setInventories(inventories);
                return b;
        }

    private SchoolEntity ensureSchool(String name, String domain) {
        return schoolRepository.findByDomain(domain)
                .map(existing -> {
                    if (!existing.isAdminApproved()) {
                        existing.setAdminApproved(true);
                        return schoolRepository.save(existing);
                    }
                    return existing;
                })
                .orElseGet(() -> {
                    SchoolEntity school = new SchoolEntity();
                    school.setName(name);
                    school.setDomain(domain);
                    school.setAdminApproved(true);
                    return schoolRepository.save(school);
                });
    }

        private List<BookInventoryEntity> createSeedInventories(BookEntity book, int totalCopies, int availableCopies) {
                List<BookInventoryEntity> inventories = new ArrayList<>();

                // We verdelen de boeken nu over 3 locaties:
                // 1. Primary school - Hoofdcampus (lege string)
                // 2. Primary school - Extra Campus
                // 3. Secondary school - Campus Zuid

                int primaryMainTotal = Math.max(1, totalCopies / 3);
                int primarySubTotal = Math.max(0, totalCopies / 3);
                int secondaryTotal = Math.max(0, totalCopies - primaryMainTotal - primarySubTotal);

                // Verdeel de beschikbare boeken op een vergelijkbare manier
                int primaryMainAvailable = Math.min(availableCopies, primaryMainTotal);
                int remainingAvailable = availableCopies - primaryMainAvailable;
                
                int primarySubAvailable = Math.min(remainingAvailable, primarySubTotal);
                int secondaryAvailable = Math.max(0, remainingAvailable - primarySubAvailable);

                // Voeg toe aan de standaard Hoofdcampus van jouw school
                addInventory(inventories, book, seedSchoolPrimary, "", primaryMainTotal, primaryMainAvailable);

                // Voeg toe aan een TWEEDE campus van jouw school (Dit is wat je nodig hebt om te testen!)
                if (primarySubTotal > 0) {
                        addInventory(inventories, book, seedSchoolPrimary, "Campus Groenenborger", primarySubTotal, primarySubAvailable);
                }

                // Voeg toe aan de tweede (andere) mock school
                if (secondaryTotal > 0) {
                        addInventory(inventories, book, seedSchoolSecondary, "Campus Zuid", secondaryTotal, secondaryAvailable);
                }

                return inventories;
        }

        private void addInventory(List<BookInventoryEntity> inventories,
                        BookEntity book,
                        SchoolEntity school,
                        String campus,
                        int totalCopies,
                        int availableCopies) {
                BookInventoryEntity inventory = new BookInventoryEntity();
                inventory.setBook(book);
                inventory.setSchool(school);
                inventory.setCampus(campus);
                inventory.setTotalCopies(totalCopies);
                inventory.setAvailableCopies(availableCopies);
                inventories.add(inventory);
        }

        @Override
        public void run(String... args) {
                if (bookRepository.count() == 0) {

                        seedSchoolPrimary = ensureSchool("https://aphogeschool.smartschool.be",
                                        "https://aphogeschool.smartschool.be");
                        seedSchoolSecondary = ensureSchool("GO! Smartbib Antwerpen", "seed-go-antwerpen.local");

                        List<BookEntity> books = List.of(
                                        book("Harry Potter and the Philosopher's Stone", List.of("J.K. Rowling"),
                                                        "Bloomsbury",
                                                        "Harry Potter has always lived a miserable life with the Dursleys, his cruel aunt and uncle. On his eleventh birthday, he learns he is a wizard and is whisked away to Hogwarts School of Witchcraft and Wizardry. There, Harry makes friends, discovers the truth about his parents, and faces the dark wizard who tried to kill him as a baby. The magical world opens up to him, but danger lurks as he unravels the mystery of the Philosopher's Stone.",
                                                        332, List.of("Fantasy", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9780747532743-L.jpg",
                                                        "en", 4.7, "9780747532743", 1997, true, false,
                                                        List.of("Vriendschap", "School & prestatiedruk"), "B", 105, 105),
                                        book("Harry Potter and the Chamber of Secrets", List.of("J.K. Rowling"),
                                                        "Bloomsbury",
                                                        "Harry's second year at Hogwarts is filled with new challenges. Strange messages appear on the walls, and students are mysteriously being petrified. With the help of Ron and Hermione, Harry investigates the legend of the Chamber of Secrets and confronts a deadly monster hidden within the school. Along the way, he learns more about his connection to Voldemort and the power of loyalty and courage.",
                                                        360, List.of("Fantasy", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9780747538486-L.jpg",
                                                        "en", 4.6, "9780747538486", 1998, false, false,
                                                        List.of("Vriendschap", "School & prestatiedruk"), "B", 6, 3),
                                        book("Harry Potter and the Prisoner of Azkaban", List.of("J.K. Rowling"),
                                                        "Bloomsbury",
                                                        "A notorious prisoner, Sirius Black, escapes from Azkaban and is believed to be after Harry. As Dementors guard the school, Harry uncovers secrets about his parents' past and the truth behind Sirius Black's escape. With the help of new magical lessons and unlikely allies, Harry faces time travel, betrayal, and the meaning of true family.",
                                                        468, List.of("Fantasy", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9780747542155-L.jpg",
                                                        "en", 4.7, "9780747542155", 1999, false, false,
                                                        List.of("Familie", "Vriendschap"), "B", 8, 6),
                                        book("Harry Potter and the Goblet of Fire", List.of("J.K. Rowling"),
                                                        "Bloomsbury",
                                                        "The wizarding world gathers for the Triwizard Tournament, a magical competition between three schools. Harry is mysteriously entered as a fourth champion and must face deadly tasks, dragons, and dark magic. As the tournament unfolds, Harry witnesses the return of Voldemort and the beginning of a new era of fear. Friendships are tested, and the stakes have never been higher.",
                                                        636, List.of("Fantasy", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780747546245-L.jpg",
                                                        "en", 4.7, "9780747546245", 2000, false, false,
                                                        List.of("Vriendschap", "School & prestatiedruk", "Overleven"),
                                                        "C", 9, 4),
                                        book("Harry Potter and the Order of the Phoenix", List.of("J.K. Rowling"),
                                                        "Bloomsbury",
                                                        "With the Ministry of Magic denying Voldemort's return, Harry and his friends form Dumbledore's Army to prepare for the battles ahead. As Hogwarts falls under the control of the cruel Dolores Umbridge, Harry struggles with visions from Voldemort and the weight of prophecy. The fight for truth and justice leads to a dramatic showdown at the Ministry, changing the wizarding world forever.",
                                                        870, List.of("Fantasy", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780747551003-L.jpg",
                                                        "en", 4.6, "9780747551003", 2003, false, false,
                                                        List.of("Vriendschap", "Macht & onrecht",
                                                                        "School & prestatiedruk"),
                                                        "C", 5, 2),
                                        book("Harry Potter and the Half-Blood Prince", List.of("J.K. Rowling"),
                                                        "Bloomsbury",
                                                        "Harry discovers an old potions textbook with mysterious annotations and learns about Voldemort's past.",
                                                        652, List.of("Fantasy", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780747581086-L.jpg",
                                                        "en", 4.6, "9780747581086", 2005, false, false,
                                                        List.of("Vriendschap", "Rouw & verlies"), "C", 7, 1),
                                        book("Harry Potter and the Deathly Hallows", List.of("J.K. Rowling"),
                                                        "Bloomsbury",
                                                        "Harry, Ron, and Hermione set out to destroy Voldemort's Horcruxes and end the war.",
                                                        759, List.of("Fantasy", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780747591054-L.jpg",
                                                        "en", 4.7, "9780747591054", 2007, true, false,
                                                        List.of("Vriendschap", "Overleven", "Rouw & verlies"), "C", 6,
                                                        5),
                                        book("The Hobbit", List.of("J.R.R. Tolkien"), "George Allen & Unwin",
                                                        "Bilbo Baggins embarks on an unexpected adventure to reclaim dwarven treasure from a dragon.",
                                                        310, List.of("Fantasy", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
                                                        "en", 4.7, "9780547928227", 1937, true, false,
                                                        List.of("Avontuur & ontdekking", "Identiteit & zelfbeeld"), "B",
                                                        4, 2),
                                        book("The Fellowship of the Ring", List.of("J.R.R. Tolkien"),
                                                        "George Allen & Unwin",
                                                        "Frodo Baggins begins his epic quest to destroy the One Ring.",
                                                        423, List.of("Fantasy", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780547928210-L.jpg",
                                                        "en", 4.7, "9780547928210", 1954, false, false,
                                                        List.of("Vriendschap", "Avontuur & ontdekking"), "C", 8, 3),
                                        book("The Two Towers", List.of("J.R.R. Tolkien"), "George Allen & Unwin",
                                                        "The fellowship is broken as the war of the Ring intensifies across Middle-earth.",
                                                        352, List.of("Fantasy", "Oorlog & conflict"),
                                                        "https://covers.openlibrary.org/b/isbn/9780547928203-L.jpg",
                                                        "en", 4.6, "9780547928203", 1954, false, false,
                                                        List.of("Vriendschap", "Overleven"), "C", 7, 4),
                                        book("The Return of the King", List.of("J.R.R. Tolkien"),
                                                        "George Allen & Unwin",
                                                        "The final battle for Middle-earth as Frodo reaches Mount Doom.",
                                                        416, List.of("Fantasy", "Oorlog & conflict"),
                                                        "https://covers.openlibrary.org/b/isbn/9780547928197-L.jpg",
                                                        "en", 4.7, "9780547928197", 1955, false, false,
                                                        List.of("Vriendschap", "Overleven", "Rouw & verlies"), "C", 6,
                                                        1),
                                        book("The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
                                                        List.of("C.S. Lewis"), "Geoffrey Bles",
                                                        "Four children discover a magical land through a wardrobe and help Aslan defeat the White Witch.",
                                                        206, List.of("Fantasy", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780064404990-L.jpg",
                                                        "en", 4.6, "9780064404990", 1950, true, false,
                                                        List.of("Familie", "Avontuur & ontdekking"), "A", 5, 4),
                                        book("A Game of Thrones", List.of("George R.R. Martin"), "Bantam Books",
                                                        "Noble families vie for control of the Iron Throne in a brutal medieval fantasy world.",
                                                        694, List.of("Fantasy", "Spanning / thriller"),
                                                        "https://covers.openlibrary.org/b/isbn/9780553573404-L.jpg",
                                                        "en", 4.5, "9780553573404", 1996, false, false,
                                                        List.of("Macht & onrecht", "Familie"), "D", 9, 7),
                                        book("The Name of the Wind", List.of("Patrick Rothfuss"), "DAW Books",
                                                        "Kvothe recounts his transformation from a young outcast to the most notorious wizard of his age.",
                                                        662, List.of("Fantasy", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg",
                                                        "en", 4.6, "9780756404741", 2007, false, false,
                                                        List.of("Identiteit & zelfbeeld", "Avontuur & ontdekking"), "C",
                                                        4, 1),
                                        book("Percy Jackson and the Lightning Thief", List.of("Rick Riordan"),
                                                        "Disney Hyperion",
                                                        "A twelve-year-old discovers he is the son of Poseidon and must find Zeus's stolen lightning bolt.",
                                                        377, List.of("Fantasy", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780786838653-L.jpg",
                                                        "en", 4.5, "9780786838653", 2005, true, false,
                                                        List.of("Identiteit & zelfbeeld", "Vriendschap",
                                                                        "Avontuur & ontdekking"),
                                                        "A", 8, 5),
                                        book("Dune", List.of("Frank Herbert"), "Chilton Books",
                                                        "A young noble must navigate the dangerous politics and ecology of a desert planet.",
                                                        688, List.of("Sciencefiction", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
                                                        "en", 4.6, "9780441172719", 1965, true, false,
                                                        List.of("Macht & onrecht", "Toekomst & technologie",
                                                                        "Overleven"),
                                                        "D", 7, 2),
                                        book("1984", List.of("George Orwell"), "Secker & Warburg",
                                                        "A dystopian novel about totalitarian surveillance and the suppression of truth.",
                                                        328, List.of("Dystopie", "Sciencefiction"),
                                                        "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
                                                        "en", 4.7, "9780451524935", 1949, true, true,
                                                        List.of("Macht & onrecht", "Toekomst & technologie"), "C", 6,
                                                        4),
                                        book("Brave New World", List.of("Aldous Huxley"), "Chatto & Windus",
                                                        "A futuristic society where humans are genetically modified and socially conditioned for stability.",
                                                        288, List.of("Dystopie", "Sciencefiction"),
                                                        "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
                                                        "en", 4.4, "9780060850524", 1932, false, true,
                                                        List.of("Macht & onrecht", "Toekomst & technologie"), "C", 5,
                                                        1),
                                        book("Fahrenheit 451", List.of("Ray Bradbury"), "Ballantine Books",
                                                        "In a future where books are banned, a fireman begins to question his role in burning them.",
                                                        194, List.of("Dystopie", "Sciencefiction"),
                                                        "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg",
                                                        "en", 4.4, "9781451673319", 1953, true, true,
                                                        List.of("Macht & onrecht", "Toekomst & technologie"), "B", 7,
                                                        3),
                                        book("The Hitchhiker's Guide to the Galaxy", List.of("Douglas Adams"),
                                                        "Pan Books",
                                                        "Arthur Dent is swept off Earth moments before its destruction for a galactic highway.",
                                                        224, List.of("Sciencefiction", "Humor"),
                                                        "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
                                                        "en", 4.6, "9780345391803", 1979, false, false,
                                                        List.of("Avontuur & ontdekking", "Toekomst & technologie"), "B",
                                                        4, 3),
                                        book("Ender's Game", List.of("Orson Scott Card"), "Tor Books",
                                                        "A gifted child is sent to military school in space to prepare for an alien invasion.",
                                                        324, List.of("Sciencefiction", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9780812550702-L.jpg",
                                                        "en", 4.6, "9780812550702", 1985, false, false,
                                                        List.of("School & prestatiedruk", "Overleven"), "B", 8, 2),
                                        book("The Hunger Games", List.of("Suzanne Collins"), "Scholastic",
                                                        "In a dystopian future, teenagers are forced to fight to the death in a televised competition.",
                                                        374, List.of("Dystopie", "Sciencefiction"),
                                                        "https://covers.openlibrary.org/b/isbn/9780439023481-L.jpg",
                                                        "en", 4.5, "9780439023481", 2008, true, true,
                                                        List.of("Macht & onrecht", "Overleven", "Sociale media"), "B",
                                                        9, 6),
                                        book("Catching Fire", List.of("Suzanne Collins"), "Scholastic",
                                                        "Katniss Everdeen becomes a symbol of rebellion against the oppressive Capitol.",
                                                        391, List.of("Dystopie", "Sciencefiction"),
                                                        "https://covers.openlibrary.org/b/isbn/9780439023498-L.jpg",
                                                        "en", 4.4, "9780439023498", 2009, false, false,
                                                        List.of("Macht & onrecht", "Overleven"), "B", 6, 2),
                                        book("Mockingjay", List.of("Suzanne Collins"), "Scholastic",
                                                        "Katniss leads a revolution against the Capitol in the final installment of the series.",
                                                        390, List.of("Dystopie", "Sciencefiction"),
                                                        "https://covers.openlibrary.org/b/isbn/9780439023511-L.jpg",
                                                        "en", 4.3, "9780439023511", 2010, false, false,
                                                        List.of("Macht & onrecht", "Overleven", "Rouw & verlies"), "B",
                                                        5, 3),
                                        book("The Maze Runner", List.of("James Dashner"), "Delacorte Press",
                                                        "A teenager wakes up in a mysterious maze with no memory and must find a way out.",
                                                        375, List.of("Sciencefiction", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780385737944-L.jpg",
                                                        "en", 4.3, "9780385737944", 2009, false, false,
                                                        List.of("Overleven", "Identiteit & zelfbeeld"), "B", 7, 5),
                                        book("Divergent", List.of("Veronica Roth"), "Katherine Tegen Books",
                                                        "In a society divided into factions, one girl discovers she doesn't fit into any single group.",
                                                        487, List.of("Dystopie", "Sciencefiction"),
                                                        "https://covers.openlibrary.org/b/isbn/9780062024039-L.jpg",
                                                        "en", 4.3, "9780062024039", 2011, false, false,
                                                        List.of("Identiteit & zelfbeeld", "Macht & onrecht"), "B", 8,
                                                        4),
                                        book("The Giver", List.of("Lois Lowry"), "Houghton Mifflin",
                                                        "A boy in a seemingly perfect society discovers the dark truth behind his community's sameness.",
                                                        208, List.of("Dystopie", "Sciencefiction"),
                                                        "https://covers.openlibrary.org/b/isbn/9780544336261-L.jpg",
                                                        "en", 4.5, "9780544336261", 1993, false, true,
                                                        List.of("Identiteit & zelfbeeld", "Macht & onrecht"), "B", 4,
                                                        1),
                                        book("Ready Player One", List.of("Ernest Cline"), "Crown Publishers",
                                                        "In a bleak future, a teenager searches for an Easter egg hidden inside a vast virtual reality.",
                                                        374, List.of("Sciencefiction", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780307887443-L.jpg",
                                                        "en", 4.3, "9780307887443", 2011, false, false,
                                                        List.of("Toekomst & technologie", "Avontuur & ontdekking"), "B",
                                                        9, 8),
                                        book("To Kill a Mockingbird", List.of("Harper Lee"), "J.B. Lippincott & Co.",
                                                        "A young girl in the American South witnesses her father defend a Black man accused of a crime.",
                                                        336, List.of("Literaire roman", "Historische roman"),
                                                        "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
                                                        "en", 4.7, "9780061120084", 1960, true, true,
                                                        List.of("Diversiteit & inclusie", "Macht & onrecht", "Familie"),
                                                        "C", 6, 5),
                                        book("The Great Gatsby", List.of("F. Scott Fitzgerald"),
                                                        "Charles Scribner's Sons",
                                                        "A mysterious millionaire's obsession with a beautiful woman in the Jazz Age.",
                                                        180, List.of("Literaire roman", "Historische roman"),
                                                        "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
                                                        "en", 4.4, "9780743273565", 1925, true, false,
                                                        List.of("Liefde & relaties", "Armoede & ongelijkheid"), "C", 5,
                                                        2),
                                        book("Pride and Prejudice", List.of("Jane Austen"), "T. Egerton",
                                                        "Elizabeth Bennet navigates love, class, and misunderstandings in Regency-era England.",
                                                        432, List.of("Literaire roman", "Romantiek"),
                                                        "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
                                                        "en", 4.6, "9780141439518", 1813, false, false,
                                                        List.of("Liefde & relaties", "Familie"), "C", 8, 6),
                                        book("Jane Eyre", List.of("Charlotte Brontë"), "Smith, Elder & Co.",
                                                        "An orphaned governess finds love and independence at the brooding Thornfield Hall.",
                                                        532, List.of("Literaire roman", "Romantiek"),
                                                        "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg",
                                                        "en", 4.5, "9780141441146", 1847, false, false,
                                                        List.of("Liefde & relaties", "Identiteit & zelfbeeld",
                                                                        "Familie"),
                                                        "C", 7, 1),
                                        book("Wuthering Heights", List.of("Emily Brontë"), "Thomas Cautley Newby",
                                                        "A tale of passionate and destructive love on the Yorkshire moors.",
                                                        416, List.of("Literaire roman", "Romantiek"),
                                                        "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg",
                                                        "en", 4.3, "9780141439556", 1847, false, false,
                                                        List.of("Liefde & relaties", "Rouw & verlies"), "C", 4, 2),
                                        book("The Catcher in the Rye", List.of("J.D. Salinger"),
                                                        "Little, Brown and Company",
                                                        "A disillusioned teenager wanders New York City after being expelled from prep school.",
                                                        234, List.of("Literaire roman", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
                                                        "en", 4.3, "9780316769488", 1951, false, true,
                                                        List.of("Identiteit & zelfbeeld", "Mentale gezondheid",
                                                                        "School & prestatiedruk"),
                                                        "C", 6, 3),
                                        book("Lord of the Flies", List.of("William Golding"), "Faber and Faber",
                                                        "Stranded boys on an island descend into savagery without adult supervision.",
                                                        224, List.of("Literaire roman", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780399501487-L.jpg",
                                                        "en", 4.3, "9780399501487", 1954, false, true,
                                                        List.of("Overleven", "Macht & onrecht"), "C", 9, 4),
                                        book("Of Mice and Men", List.of("John Steinbeck"), "Covici Friede",
                                                        "Two displaced migrant workers dream of owning their own piece of land during the Great Depression.",
                                                        107, List.of("Literaire roman", "Historische roman"),
                                                        "https://covers.openlibrary.org/b/isbn/9780140186420-L.jpg",
                                                        "en", 4.4, "9780140186420", 1937, false, true,
                                                        List.of("Vriendschap", "Armoede & ongelijkheid",
                                                                        "Rouw & verlies"),
                                                        "B", 5, 1),
                                        book("Animal Farm", List.of("George Orwell"), "Secker & Warburg",
                                                        "A political allegory in which farm animals overthrow their human owner only to face new tyranny.",
                                                        112, List.of("Literaire roman", "Humor"),
                                                        "https://covers.openlibrary.org/b/isbn/9780451526342-L.jpg",
                                                        "en", 4.5, "9780451526342", 1945, false, true,
                                                        List.of("Macht & onrecht"), "B", 7, 6),
                                        book("The Adventures of Huckleberry Finn", List.of("Mark Twain"),
                                                        "Chatto & Windus",
                                                        "A boy and a runaway slave travel down the Mississippi River seeking freedom.",
                                                        366, List.of("Literaire roman", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780142437179-L.jpg",
                                                        "en", 4.3, "9780142437179", 1884, false, false,
                                                        List.of("Diversiteit & inclusie", "Avontuur & ontdekking"), "C",
                                                        8, 5),
                                        book("Great Expectations", List.of("Charles Dickens"), "Chapman & Hall",
                                                        "An orphan named Pip navigates social class and personal growth in Victorian England.",
                                                        544, List.of("Literaire roman", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9780141439563-L.jpg",
                                                        "en", 4.3, "9780141439563", 1861, false, false,
                                                        List.of("Identiteit & zelfbeeld", "Armoede & ongelijkheid"),
                                                        "C", 6, 2),
                                        book("A Tale of Two Cities", List.of("Charles Dickens"), "Chapman & Hall",
                                                        "A story of love and sacrifice set against the backdrop of the French Revolution.",
                                                        489, List.of("Literaire roman", "Historische roman"),
                                                        "https://covers.openlibrary.org/b/isbn/9780141439600-L.jpg",
                                                        "en", 4.4, "9780141439600", 1859, false, false,
                                                        List.of("Liefde & relaties", "Oorlog & conflict"), "C", 4, 3),
                                        book("Romeo and Juliet", List.of("William Shakespeare"), "Various",
                                                        "The tragic love story of two young people from feuding families in Verona.",
                                                        320, List.of("Literaire roman", "Romantiek"),
                                                        "https://covers.openlibrary.org/b/isbn/9780743477116-L.jpg",
                                                        "en", 4.4, "9780743477116", 1597, false, false,
                                                        List.of("Liefde & relaties", "Familie", "Rouw & verlies"), "C",
                                                        5, 4),
                                        book("Hamlet", List.of("William Shakespeare"), "Various",
                                                        "The Prince of Denmark seeks revenge after his father's murder by his uncle.",
                                                        342, List.of("Literaire roman", "Spanning / thriller"),
                                                        "https://covers.openlibrary.org/b/isbn/9780743477123-L.jpg",
                                                        "en", 4.5, "9780743477123", 1603, false, true,
                                                        List.of("Familie", "Rouw & verlies", "Macht & onrecht"), "D", 7,
                                                        2),
                                        book("Macbeth", List.of("William Shakespeare"), "Various",
                                                        "A Scottish general's ambition leads to murder, guilt, and his ultimate downfall.",
                                                        256, List.of("Literaire roman", "Spanning / thriller"),
                                                        "https://covers.openlibrary.org/b/isbn/9780743477109-L.jpg",
                                                        "en", 4.4, "9780743477109", 1606, false, false,
                                                        List.of("Macht & onrecht", "Mentale gezondheid"), "D", 8, 1),
                                        book("The Odyssey", List.of("Homer"), "Various",
                                                        "Odysseus's epic journey home after the Trojan War, facing monsters and divine obstacles.",
                                                        541, List.of("Avontuur", "Literaire roman"),
                                                        "https://covers.openlibrary.org/b/isbn/9780140268867-L.jpg",
                                                        "en", 4.4, "9780140268867", -800, false, false,
                                                        List.of("Avontuur & ontdekking", "Overleven", "Familie"), "D",
                                                        6, 4),
                                        book("Frankenstein", List.of("Mary Shelley"),
                                                        "Lackington, Hughes, Harding, Mavor & Jones",
                                                        "A scientist creates a sapient creature, leading to tragic consequences for both.",
                                                        280, List.of("Horror", "Sciencefiction"),
                                                        "https://covers.openlibrary.org/b/isbn/9780141439471-L.jpg",
                                                        "en", 4.3, "9780141439471", 1818, false, true,
                                                        List.of("Identiteit & zelfbeeld", "Rouw & verlies",
                                                                        "Toekomst & technologie"),
                                                        "C", 9, 5),
                                        book("Dracula", List.of("Bram Stoker"), "Archibald Constable and Company",
                                                        "A vampire count from Transylvania stalks his prey in Victorian England.",
                                                        418, List.of("Horror", "Spanning / thriller"),
                                                        "https://covers.openlibrary.org/b/isbn/9780141439846-L.jpg",
                                                        "en", 4.3, "9780141439846", 1897, false, false,
                                                        List.of("Overleven"), "C", 5, 2),
                                        book("The Fault in Our Stars", List.of("John Green"), "Dutton Books",
                                                        "Two teenagers with cancer fall in love and travel to Amsterdam for one last adventure.",
                                                        313, List.of("Romantiek", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9780525478812-L.jpg",
                                                        "en", 4.4, "9780525478812", 2012, false, false,
                                                        List.of("Liefde & relaties", "Mentale gezondheid",
                                                                        "Rouw & verlies"),
                                                        "B", 7, 3),
                                        book("The Book Thief", List.of("Markus Zusak"), "Picador",
                                                        "Narrated by Death, a girl in Nazi Germany finds solace by stealing books.",
                                                        584, List.of("Historische roman", "Literaire roman"),
                                                        "https://covers.openlibrary.org/b/isbn/9780375842207-L.jpg",
                                                        "en", 4.6, "9780375842207", 2005, true, true,
                                                        List.of("Oorlog & conflict", "Rouw & verlies", "Familie"), "C",
                                                        8, 7),
                                        book("The Kite Runner", List.of("Khaled Hosseini"), "Riverhead Books",
                                                        "An Afghan man confronts his past betrayal and seeks redemption in war-torn Afghanistan.",
                                                        371, List.of("Historische roman", "Literaire roman"),
                                                        "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
                                                        "en", 4.5, "9781594631931", 2003, false, true,
                                                        List.of("Migratie & afkomst", "Vriendschap", "Rouw & verlies"),
                                                        "C", 6, 1),
                                        book("Life of Pi", List.of("Yann Martel"), "Knopf Canada",
                                                        "A boy is stranded on a lifeboat in the Pacific Ocean with a Bengal tiger.",
                                                        460, List.of("Avontuur", "Literaire roman"),
                                                        "https://covers.openlibrary.org/b/isbn/9780156027328-L.jpg",
                                                        "en", 4.4, "9780156027328", 2001, false, false,
                                                        List.of("Overleven", "Avontuur & ontdekking"), "C", 4, 2),
                                        book("The Alchemist", List.of("Paulo Coelho"), "HarperOne",
                                                        "A young Andalusian shepherd follows his dreams on a journey to the Egyptian pyramids.",
                                                        197, List.of("Literaire roman", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
                                                        "en", 4.3, "9780062315007", 1988, false, false,
                                                        List.of("Identiteit & zelfbeeld", "Avontuur & ontdekking"), "B",
                                                        5, 3),
                                        book("The Perks of Being a Wallflower", List.of("Stephen Chbosky"), "MTV Books",
                                                        "An introverted teen navigates high school life through a series of anonymous letters.",
                                                        213, List.of("Coming-of-age", "Literaire roman"),
                                                        "https://covers.openlibrary.org/b/isbn/9781451696196-L.jpg",
                                                        "en", 4.4, "9781451696196", 1999, false, true,
                                                        List.of("Mentale gezondheid", "Vriendschap",
                                                                        "School & prestatiedruk"),
                                                        "B", 7, 4),
                                        book("Wonder", List.of("R.J. Palacio"), "Knopf Books for Young Readers",
                                                        "A boy with facial differences attends mainstream school for the first time.",
                                                        315, List.of("Coming-of-age", "Fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780375869020-L.jpg",
                                                        "en", 4.6, "9780375869020", 2012, true, true,
                                                        List.of("Diversiteit & inclusie", "School & prestatiedruk",
                                                                        "Familie"),
                                                        "A", 8, 6),
                                        book("The Curious Incident of the Dog in the Night-Time",
                                                        List.of("Mark Haddon"), "Jonathan Cape",
                                                        "A boy with autism investigates the death of a neighbor's dog and uncovers family secrets.",
                                                        226, List.of("Detective / misdaad", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9781400032716-L.jpg",
                                                        "en", 4.3, "9781400032716", 2003, false, true,
                                                        List.of("Mentale gezondheid", "Familie",
                                                                        "Identiteit & zelfbeeld"),
                                                        "B", 6, 2),
                                        book("Holes", List.of("Louis Sachar"), "Farrar, Straus and Giroux",
                                                        "A boy is sent to a juvenile detention camp where inmates dig holes all day.",
                                                        233, List.of("Avontuur", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9780440414803-L.jpg",
                                                        "en", 4.5, "9780440414803", 1998, false, false,
                                                        List.of("Vriendschap", "Macht & onrecht"), "A", 5, 1),
                                        book("Matilda", List.of("Roald Dahl"), "Jonathan Cape",
                                                        "A brilliant little girl uses her intelligence and telekinetic powers to overcome her awful parents and headmistress.",
                                                        240, List.of("Fantasy", "Coming-of-age"),
                                                        "https://covers.openlibrary.org/b/isbn/9780142410370-L.jpg",
                                                        "en", 4.6, "9780142410370", 1988, false, false,
                                                        List.of("Familie", "School & prestatiedruk",
                                                                        "Identiteit & zelfbeeld"),
                                                        "A", 9, 8),
                                        book("Charlie and the Chocolate Factory", List.of("Roald Dahl"),
                                                        "Alfred A. Knopf",
                                                        "A poor boy wins a tour of the most magnificent chocolate factory in the world.",
                                                        176, List.of("Fantasy", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780142410318-L.jpg",
                                                        "en", 4.6, "9780142410318", 1964, false, false,
                                                        List.of("Familie", "Armoede & ongelijkheid"), "A", 7, 5),
                                        book("Charlotte's Web", List.of("E.B. White"), "Harper & Brothers",
                                                        "A spider named Charlotte saves her pig friend Wilbur from slaughter through her webs.",
                                                        184, List.of("Fantasy", "Fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780064400558-L.jpg",
                                                        "en", 4.6, "9780064400558", 1952, false, false,
                                                        List.of("Vriendschap", "Rouw & verlies"), "A", 4, 1),
                                        book("The Little Prince", List.of("Antoine de Saint-Exupéry"),
                                                        "Reynal & Hitchcock",
                                                        "A pilot stranded in the Sahara meets a young prince from a tiny asteroid.",
                                                        96, List.of("Fictie algemeen", "Avontuur"),
                                                        "https://covers.openlibrary.org/b/isbn/9780156012195-L.jpg",
                                                        "en", 4.7, "9780156012195", 1943, true, true,
                                                        List.of("Vriendschap", "Identiteit & zelfbeeld",
                                                                        "Rouw & verlies"),
                                                        "A", 6, 5),
                                        book("A Brief History of Time", List.of("Stephen Hawking"), "Bantam Dell",
                                                        "An accessible exploration of cosmology, black holes, and the nature of time.",
                                                        256, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
                                                        "en", 4.6, "9780553380163", 1988, true, true,
                                                        List.of("Toekomst & technologie", "Avontuur & ontdekking"), "C",
                                                        8, 3),
                                        book("Cosmos", List.of("Carl Sagan"), "Random House",
                                                        "A sweeping journey through the universe exploring science, civilization, and our place in the cosmos.",
                                                        396, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780345539434-L.jpg",
                                                        "en", 4.6, "9780345539434", 1980, false, true,
                                                        List.of("Avontuur & ontdekking", "Toekomst & technologie"), "C",
                                                        7, 4),
                                        book("The Selfish Gene", List.of("Richard Dawkins"), "Oxford University Press",
                                                        "A groundbreaking look at evolution from the gene's perspective.",
                                                        360, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780199291151-L.jpg",
                                                        "en", 4.4, "9780199291151", 1976, false, false,
                                                        List.of("Avontuur & ontdekking"), "D", 5, 2),
                                        book("Sapiens: A Brief History of Humankind", List.of("Yuval Noah Harari"),
                                                        "Harper",
                                                        "A sweeping narrative of human history from the Stone Age to the present.",
                                                        443, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
                                                        "en", 4.5, "9780062316097", 2011, true, true,
                                                        List.of("Diversiteit & inclusie", "Migratie & afkomst",
                                                                        "Avontuur & ontdekking"),
                                                        "C", 9, 6),
                                        book("The Origin of Species", List.of("Charles Darwin"), "John Murray",
                                                        "Darwin's foundational work on the theory of evolution by natural selection.",
                                                        502, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780451529060-L.jpg",
                                                        "en", 4.3, "9780451529060", 1859, false, true,
                                                        List.of("Avontuur & ontdekking"), "D", 6, 1),
                                        book("Silent Spring", List.of("Rachel Carson"), "Houghton Mifflin",
                                                        "A landmark work documenting the environmental damage caused by pesticides.",
                                                        378, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780618249060-L.jpg",
                                                        "en", 4.4, "9780618249060", 1962, false, true,
                                                        List.of("Macht & onrecht"), "C", 4, 2),
                                        book("The Immortal Life of Henrietta Lacks", List.of("Rebecca Skloot"), "Crown",
                                                        "The story of the woman whose cells were taken without consent and became vital for medical research.",
                                                        381, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9781400052189-L.jpg",
                                                        "en", 4.5, "9781400052189", 2010, false, true,
                                                        List.of("Macht & onrecht", "Diversiteit & inclusie"), "C", 8,
                                                        7),
                                        book("Astrophysics for People in a Hurry", List.of("Neil deGrasse Tyson"),
                                                        "W. W. Norton",
                                                        "A concise guide to the most important ideas in astrophysics.",
                                                        224, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780393609394-L.jpg",
                                                        "en", 4.3, "9780393609394", 2017, false, false,
                                                        List.of("Toekomst & technologie", "Avontuur & ontdekking"), "B",
                                                        5, 3),
                                        book("Fermat's Last Theorem", List.of("Simon Singh"), "Fourth Estate",
                                                        "The riveting story of how Andrew Wiles proved Fermat's famous conjecture.",
                                                        340, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9781841157917-L.jpg",
                                                        "en", 4.5, "9781841157917", 1997, false, false,
                                                        List.of("School & prestatiedruk", "Identiteit & zelfbeeld"),
                                                        "C", 7, 2),
                                        book("Flatland: A Romance of Many Dimensions", List.of("Edwin A. Abbott"),
                                                        "Seeley & Co.",
                                                        "A satirical novella exploring dimensions through life in a two-dimensional world.",
                                                        96, List.of("Sciencefiction", "Humor"),
                                                        "https://covers.openlibrary.org/b/isbn/9780486272634-L.jpg",
                                                        "en", 4.2, "9780486272634", 1884, false, false,
                                                        List.of("Identiteit & zelfbeeld", "Toekomst & technologie"),
                                                        "B", 6, 4),
                                        book("Night", List.of("Elie Wiesel"), "Hill & Wang",
                                                        "A harrowing memoir of survival in the Auschwitz and Buchenwald concentration camps.",
                                                        120, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780374500016-L.jpg",
                                                        "en", 4.6, "9780374500016", 1956, false, true,
                                                        List.of("Overleven", "Rouw & verlies", "Oorlog & conflict"),
                                                        "C", 9, 5),
                                        book("Guns, Germs, and Steel", List.of("Jared Diamond"), "W. W. Norton",
                                                        "An exploration of why some civilizations conquered others through geography, technology, and biology.",
                                                        480, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg",
                                                        "en", 4.3, "9780393317558", 1997, false, true,
                                                        List.of("Macht & onrecht", "Armoede & ongelijkheid"), "D", 4,
                                                        1),
                                        book("A People's History of the United States", List.of("Howard Zinn"),
                                                        "Harper & Row",
                                                        "American history told from the perspective of marginalized groups rather than political leaders.",
                                                        729, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780060838652-L.jpg",
                                                        "en", 4.4, "9780060838652", 1980, false, true,
                                                        List.of("Macht & onrecht", "Diversiteit & inclusie",
                                                                        "Armoede & ongelijkheid"),
                                                        "D", 8, 5),
                                        book("The Art of War", List.of("Sun Tzu"), "Various",
                                                        "An ancient Chinese military treatise on strategy and tactics.",
                                                        273, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9781590302255-L.jpg",
                                                        "en", 4.3, "9781590302255", -500, false, false,
                                                        List.of("Macht & onrecht", "Oorlog & conflict"), "C", 6, 2),
                                        book("Thinking, Fast and Slow", List.of("Daniel Kahneman"),
                                                        "Farrar, Straus and Giroux",
                                                        "A Nobel laureate explores the two systems that drive the way we think.",
                                                        499, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
                                                        "en", 4.4, "9780374533557", 2011, false, false,
                                                        List.of("Identiteit & zelfbeeld"), "D", 5, 4),
                                        book("Man's Search for Meaning", List.of("Viktor E. Frankl"), "Beacon Press",
                                                        "A psychiatrist's memoir of surviving the Holocaust and finding purpose through suffering.",
                                                        184, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg",
                                                        "en", 4.7, "9780807014295", 1946, true, true,
                                                        List.of("Mentale gezondheid", "Rouw & verlies", "Overleven"),
                                                        "C", 7, 3),
                                        book("The Republic", List.of("Plato"), "Various",
                                                        "Plato's foundational work on justice, the ideal state, and the nature of reality.",
                                                        416, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780140455113-L.jpg",
                                                        "en", 4.3, "9780140455113", -380, false, true,
                                                        List.of("Macht & onrecht"), "D", 9, 6),
                                        book("Meditations", List.of("Marcus Aurelius"), "Various",
                                                        "Personal reflections by the Roman Emperor on Stoic philosophy and self-improvement.",
                                                        256, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780140449334-L.jpg",
                                                        "en", 4.5, "9780140449334", 180, false, false,
                                                        List.of("Identiteit & zelfbeeld", "Mentale gezondheid"), "C", 4,
                                                        2),
                                        book("The Autobiography of Malcolm X", List.of("Malcolm X", "Alex Haley"),
                                                        "Grove Press",
                                                        "The life story of the civil rights leader, from his troubled youth to his transformation.",
                                                        500, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780345350688-L.jpg",
                                                        "en", 4.6, "9780345350688", 1965, false, true,
                                                        List.of("Diversiteit & inclusie", "Macht & onrecht",
                                                                        "Identiteit & zelfbeeld"),
                                                        "C", 8, 4),
                                        book("Long Walk to Freedom", List.of("Nelson Mandela"),
                                                        "Little, Brown and Company",
                                                        "Nelson Mandela's autobiography detailing his struggle against apartheid in South Africa.",
                                                        656, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg",
                                                        "en", 4.6, "9780316548182", 1994, false, true,
                                                        List.of("Diversiteit & inclusie", "Macht & onrecht",
                                                                        "Overleven"),
                                                        "D", 6, 5),
                                        book("Steve Jobs", List.of("Walter Isaacson"), "Simon & Schuster",
                                                        "The authorized biography of the co-founder of Apple, based on extensive interviews.",
                                                        656, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg",
                                                        "en", 4.4, "9781451648539", 2011, false, false,
                                                        List.of("Toekomst & technologie", "Identiteit & zelfbeeld"),
                                                        "C", 5, 1),
                                        book("I Know Why the Caged Bird Sings", List.of("Maya Angelou"), "Random House",
                                                        "Maya Angelou's powerful memoir of growing up as a Black girl in the American South.",
                                                        289, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780345514400-L.jpg",
                                                        "en", 4.5, "9780345514400", 1969, false, true,
                                                        List.of("Diversiteit & inclusie", "Identiteit & zelfbeeld",
                                                                        "Familie"),
                                                        "C", 7, 6),
                                        book("Educated", List.of("Tara Westover"), "Random House",
                                                        "A memoir about a woman who grows up in a survivalist family and eventually earns a PhD from Cambridge.",
                                                        334, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
                                                        "en", 4.5, "9780399590504", 2018, false, true,
                                                        List.of("Familie", "School & prestatiedruk",
                                                                        "Identiteit & zelfbeeld"),
                                                        "C", 8, 3),
                                        book("Becoming", List.of("Michelle Obama"), "Crown",
                                                        "The former First Lady's memoir covering her roots, career, and time in the White House.",
                                                        448, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg",
                                                        "en", 4.5, "9781524763138", 2018, false, false,
                                                        List.of("Identiteit & zelfbeeld", "Familie"), "C", 4, 1),
                                        book("Clean Code", List.of("Robert C. Martin"), "Prentice Hall",
                                                        "A handbook of agile software craftsmanship focusing on writing maintainable code.",
                                                        464, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg",
                                                        "en", 4.7, "9780132350884", 2008, true, true,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "C", 9, 7),
                                        book("The Pragmatic Programmer", List.of("Andrew Hunt", "David Thomas"),
                                                        "Addison-Wesley",
                                                        "Classic guide for pragmatic and effective software development practices.",
                                                        352, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780201616224-L.jpg",
                                                        "en", 4.6, "9780201616224", 1999, false, false,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "C", 6, 2),
                                        book("Design Patterns: Elements of Reusable Object-Oriented Software",
                                                        List.of("Erich Gamma", "Richard Helm", "Ralph Johnson",
                                                                        "John Vlissides"),
                                                        "Addison-Wesley",
                                                        "The original Gang of Four book introducing foundational design patterns.",
                                                        395, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg",
                                                        "en", 4.5, "9780201633610", 1994, false, false,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "D", 5, 3),
                                        book("Effective Java", List.of("Joshua Bloch"), "Addison-Wesley",
                                                        "Best practices and expert recommendations for writing robust Java code.",
                                                        416, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780134685991-L.jpg",
                                                        "en", 4.8, "9780134685991", 2018, true, true,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "C", 7, 5),
                                        book("Introduction to Algorithms",
                                                        List.of("Thomas H. Cormen", "Charles E. Leiserson",
                                                                        "Ronald L. Rivest", "Clifford Stein"),
                                                        "MIT Press",
                                                        "Widely used textbook covering a broad range of algorithms in depth.",
                                                        1312, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg",
                                                        "en", 4.6, "9780262033848", 2009, false, true,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "D", 8, 4),
                                        book("Clean Architecture", List.of("Robert C. Martin"), "Prentice Hall",
                                                        "A guide to building scalable and maintainable software architecture.",
                                                        432, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780134494166-L.jpg",
                                                        "en", 4.4, "9780134494166", 2017, false, false,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "C", 6, 1),
                                        book("Refactoring", List.of("Martin Fowler"), "Addison-Wesley",
                                                        "Improving the design of existing code through structured refactoring techniques.",
                                                        448, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780201485677-L.jpg",
                                                        "en", 4.5, "9780201485677", 1999, false, false,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "C", 4, 3),
                                        book("The Clean Coder", List.of("Robert C. Martin"), "Prentice Hall",
                                                        "A code of conduct for professional programmers.", 256,
                                                        List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780137081073-L.jpg",
                                                        "en", 4.3, "9780137081073", 2011, false, false,
                                                        List.of("School & prestatiedruk"), "B", 5, 2),
                                        book("Head First Design Patterns", List.of("Eric Freeman", "Elisabeth Robson"),
                                                        "O'Reilly Media",
                                                        "A visually rich introduction to design patterns in software development.",
                                                        694, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780596007126-L.jpg",
                                                        "en", 4.6, "9780596007126", 2004, false, false,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "C", 9, 8),
                                        book("Spring in Action", List.of("Craig Walls"), "Manning",
                                                        "Comprehensive guide to developing applications using the Spring Framework.",
                                                        520, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9781617294945-L.jpg",
                                                        "en", 4.4, "9781617294945", 2018, false, false,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "C", 7, 4),
                                        book("You Don't Know JS Yet", List.of("Kyle Simpson"),
                                                        "Independently published",
                                                        "Deep dive into JavaScript core mechanisms and advanced concepts.",
                                                        143, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9781091210099-L.jpg",
                                                        "en", 4.4, "9781091210099", 2020, false, false,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "B", 6, 2),
                                        book("Domain-Driven Design", List.of("Eric Evans"), "Addison-Wesley",
                                                        "Tackling complexity in the heart of software with domain-driven design.",
                                                        560, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780321125217-L.jpg",
                                                        "en", 4.5, "9780321125217", 2003, false, false,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "D", 8, 6),
                                        book("Structure and Interpretation of Computer Programs",
                                                        List.of("Harold Abelson", "Gerald Jay Sussman"), "MIT Press",
                                                        "A classic computer science text using Scheme to teach fundamental programming concepts.",
                                                        657, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780262510875-L.jpg",
                                                        "en", 4.6, "9780262510875", 1996, false, false,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "D", 5, 1),
                                        book("Code Complete", List.of("Steve McConnell"), "Microsoft Press",
                                                        "A comprehensive handbook of software construction techniques and best practices.",
                                                        960, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780735619678-L.jpg",
                                                        "en", 4.5, "9780735619678", 2004, false, false,
                                                        List.of("School & prestatiedruk", "Toekomst & technologie"),
                                                        "D", 4, 2),
                                        book("Cracking the Coding Interview", List.of("Gayle Laakmann McDowell"),
                                                        "CareerCup",
                                                        "189 programming questions and solutions to prepare for technical interviews.",
                                                        687, List.of("Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780984782857-L.jpg",
                                                        "en", 4.4, "9780984782857", 2015, false, false,
                                                        List.of("School & prestatiedruk"), "C", 7, 3),
                                        book("The Girl with the Dragon Tattoo", List.of("Stieg Larsson"),
                                                        "Norstedts Förlag",
                                                        "A journalist and a hacker investigate a decades-old disappearance in Sweden.",
                                                        672, List.of("Detective / misdaad", "Spanning / thriller"),
                                                        "https://covers.openlibrary.org/b/isbn/9780307454546-L.jpg",
                                                        "en", 4.4, "9780307454546", 2005, false, false,
                                                        List.of("Macht & onrecht", "Overleven"), "C", 9, 5),
                                        book("Gone Girl", List.of("Gillian Flynn"), "Crown Publishing Group",
                                                        "A woman disappears on her fifth wedding anniversary, and suspicion falls on her husband.",
                                                        432, List.of("Spanning / thriller", "Detective / misdaad"),
                                                        "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg",
                                                        "en", 4.3, "9780307588371", 2012, false, false,
                                                        List.of("Liefde & relaties", "Macht & onrecht"), "C", 6, 4),
                                        book("And Then There Were None", List.of("Agatha Christie"),
                                                        "Collins Crime Club",
                                                        "Ten strangers are lured to an island where they are murdered one by one.",
                                                        272, List.of("Detective / misdaad", "Spanning / thriller"),
                                                        "https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg",
                                                        "en", 4.6, "9780062073488", 1939, false, false,
                                                        List.of("Overleven"), "B", 9, 9),
                                        book("Murder on the Orient Express", List.of("Agatha Christie"),
                                                        "Collins Crime Club",
                                                        "Detective Hercule Poirot investigates a murder on a snowbound train.",
                                                        274, List.of("Detective / misdaad"),
                                                        "https://covers.openlibrary.org/b/isbn/9780062073501-L.jpg",
                                                        "en", 4.5, "9780062073501", 1934, false, false,
                                                        List.of("Macht & onrecht"), "B", 8, 5),
                                        book("The Da Vinci Code", List.of("Dan Brown"), "Doubleday",
                                                        "A symbologist uncovers a religious mystery hidden in the works of Leonardo da Vinci.",
                                                        689, List.of("Spanning / thriller", "Detective / misdaad"),
                                                        "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
                                                        "en", 4.3, "9780307474278", 2003, false, false,
                                                        List.of("Avontuur & ontdekking"), "B", 7, 1),
                                        book("The Hound of the Baskervilles", List.of("Arthur Conan Doyle"),
                                                        "George Newnes",
                                                        "Sherlock Holmes investigates a supernatural hound haunting a family on the moors of Devon.",
                                                        256, List.of("Detective / misdaad", "Spanning / thriller"),
                                                        "https://covers.openlibrary.org/b/isbn/9780141329390-L.jpg",
                                                        "en", 4.4, "9780141329390", 1902, false, false,
                                                        List.of("Familie"), "B", 4, 3),
                                        book("It", List.of("Stephen King"), "Viking Press",
                                                        "A group of friends confronts an evil entity that takes the form of a terrifying clown.",
                                                        1138, List.of("Horror", "Spanning / thriller"),
                                                        "https://covers.openlibrary.org/b/isbn/9781501142970-L.jpg",
                                                        "en", 4.4, "9781501142970", 1986, false, false,
                                                        List.of("Vriendschap", "Overleven", "Rouw & verlies"), "D", 9,
                                                        7),
                                        book("The Shining", List.of("Stephen King"), "Doubleday",
                                                        "A family moves into an isolated hotel for the winter where a sinister presence influences the father.",
                                                        447, List.of("Horror", "Spanning / thriller"),
                                                        "https://covers.openlibrary.org/b/isbn/9780307743657-L.jpg",
                                                        "en", 4.5, "9780307743657", 1977, false, false,
                                                        List.of("Familie", "Mentale gezondheid", "Overleven"), "C", 6,
                                                        2),
                                        book("Maus", List.of("Art Spiegelman"), "Pantheon Books",
                                                        "A graphic novel depicting the author's father's experience as a Holocaust survivor, with Jews as mice and Nazis as cats.",
                                                        296, List.of("Graphic novel / strip", "Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780394747231-L.jpg",
                                                        "en", 4.7, "9780394747231", 1986, false, true,
                                                        List.of("Oorlog & conflict", "Overleven", "Rouw & verlies"),
                                                        "B", 5, 4),
                                        book("Persepolis", List.of("Marjane Satrapi"), "L'Association",
                                                        "A graphic memoir about growing up in Iran during the Islamic Revolution.",
                                                        160, List.of("Graphic novel / strip", "Non-fictie algemeen"),
                                                        "https://covers.openlibrary.org/b/isbn/9780375714573-L.jpg",
                                                        "en", 4.4, "9780375714573", 2000, false, true,
                                                        List.of("Migratie & afkomst", "Identiteit & zelfbeeld",
                                                                        "Macht & onrecht"),
                                                        "B", 7, 3));
                        Iterable<BookEntity> savedBooks = bookRepository.saveAll(books);
                        for (BookEntity savedBook : savedBooks) {
                                if (savedBook.getInventories() == null) {
                                        continue;
                                }

                                for (BookInventoryEntity inventory : savedBook.getInventories()) {
                                        List<BookCopyEntity> copies = new ArrayList<>();
                                        for (int i = 1; i <= inventory.getTotalCopies(); i++) {
                                                BookCopyEntity copy = new BookCopyEntity();
                                                copy.setInventory(inventory);
                                                copy.setCopyCondition(BookCopyCondition.GOOD);
                                                copy.setCopyNumber(i);
                                                copies.add(copy);
                                        }
                                        bookCopyRepository.saveAll(copies);
                                }
                        }
                        logger.info("Database seeded with {} books!", books.size());
                } else {
                        logger.info("Database already contains data; seeding skipped.");
                }

                for (BookInventoryEntity inventory : bookInventoryRepository.findAll()) {
                        bookService.reconcileCopiesForInventory(inventory);
                }
                logger.info("BookCopy reconcile complete.");
        }
}