app.frontend.base-url=http://localhost:3000
spring.security.oauth2.client.registration.smartschool.redirect-uri=http://localhost:8080/login/oauth2/code/smartschool

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=TRACE